#!/bin/bash

if test $# != 0 ; then
cmds=$@
fi

FLAGS="--prefix=/usr/local"
#FLAGS="$FLAGS --disable-pthread"
#FLAGS="$FLAGS --disable-mutex"

export CFLAGS="-Wall -Wno-unused-parameter -Wno-char-subscripts -Wno-pointer-sign ${CFLAGS}"

autoreconf -i --force
sh $X ./configure ${FLAGS}
for c in $cmds; do
  make $c
done
exit 0
